version: "3"

services:

  database:
    image: gmcgoldrick/hybrid_database
    # set default mysql root password, change as needed
    environment:
      MYSQL_ROOT_PASSWORD: "DockerCon!!!"
    # Expose port 3306 to host. 
    ports:
      - "3306:3306" 
    networks:
      - back-tier

  webserver:
    image: gmcgoldrick/hybrid_java_web_2
    ports:
      - "8080:8080" 
    networks:
      - front-tier
      - back-tier
    environment:
      BASEURI: http://dotnet-api/api/users

  dotnet-api:
    image: gmcgoldrick/hybrid_dotnet_api
    ports:
      - "57989:80"
    networks:
      - front-tier
      - back-tier

networks:
  back-tier:
  front-tier:
    external: true

#secrets:
#  mysql_password:
#    external: true