version: "3"

services:

  database:
    image: gmcgoldrick/hybrid_database
    # set default mysql root password, change as needed
    environment:
      MYSQL_ROOT_PASSWORD: "DockerCon!!!"
    # Expose port 3306 to host. 
    ports:
      - "3306:3306" 
    networks:
      - back-tier

  webserver:
    image: gmcgoldrick/hybrid_java_web
    ports:
      - "8080:8080" 
    networks:
      - front-tier
      - back-tier

networks:
  back-tier:
  front-tier:

#secrets:
#  mysql_password:
#    file: ./mysql_password.txt