version: "3"

services:

  database:
    image: gab-dtr.cloudra.local/java/database
    # set default mysql root password, change as needed
    environment:
      MYSQL_ROOT_PASSWORD: "DockerCon!!!"
    # Expose port 3306 to host. 
    ports:
      - "3306:3306" 
    networks:
      - back-tier

  webserver:
    image: gab-dtr.cloudra.local/java/java_web:2
    ports:
      - "8080:8080" 
    networks:
      - front-tier
      - back-tier
    environment:
      BASEURI: http://dotnet-api/api/users

  dotnet-api:
    image: gab-dtr.cloudra.local/dotnet/dotnet_api
    ports:
      - "57989:80"
    networks:
      - front-tier
      - back-tier

networks:
  back-tier:
  front-tier:

