version: '3.2'

services:

  database:
    image:  gmcgoldrick/hybrid_database
    environment:
      MYSQL_ROOT_PASSWORD: "DockerCon!!!"
    ports:
      - "3306:3306" 
    networks:
      - back-tier
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == linux

  dotnet-api:
    image: gmcgoldrick/hybrid_dotnet_api
    ports:
    - mode: host
      published: 57989
      target: 80
    networks:
      - front-tier
      - back-tier
    deploy:
      #mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
        - node.platform.os == windows

  java-web:
    image: gmcgoldrick/hybrid_java_web_2
    environment:
      BASEURI: http://dotnet-api/api/users
    ports:
      - "8089:8080" 
    networks:
      - front-tier
      - back-tier
    deploy:
      placement:
        constraints:
        - node.platform.os == linux

networks:
  back-tier: #{}
  front-tier: #{}

#secrets:
#  mysql_password:
#    file: ./secrets/mysql_password